GET http://localhost:3000/songs

###
GET http://localhost:3000/songs/1

###
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Lasting Lover",
    "artists": ["sigla", "martin", "john"],
    "releasedDate":"2022-09-23",
    "duration": "02:34"
}

###
PUT http://localhost:3000/songs/1

###
DELETE http://localhost:3000/songs/1